#!/usr/bin/env python3
"""Generate a compact per-task downstream overview grid."""

import statistics as st

from paper_utils.hybrid.downstream_results import (
    METHOD_ORDER,
    METHOD_SHORT_LABEL,
    TASK_LABEL,
    load_metric_data,
    load_rows,
    paper_methods,
    task_columns,
)
from paper_utils.hybrid.utils import paper_table_path

OUT_TEX = paper_table_path("table_downstream_tasks.tex", appendix=True, extra=True)


def _top2(values: dict[str, float]) -> tuple[str | None, str | None]:
    pairs = sorted(values.items(), key=lambda item: item[1], reverse=True)
    best = pairs[0][0] if pairs else None
    second = pairs[1][0] if len(pairs) > 1 else None
    return best, second


def _cell(value: float, method: str, best: str | None, second: str | None) -> str:
    text = f"{value * 100.0:.1f}"
    if method == best:
        return f"\\cellcolor{{ForestGreen!18}}\\textbf{{{text}}}"
    if method == second:
        return f"\\cellcolor{{Goldenrod!14}}\\underline{{{text}}}"
    return text


def main() -> None:
    rows = load_rows()
    data = load_metric_data()
    methods = paper_methods(data)
    method_rank = {method: i for i, method in enumerate(METHOD_ORDER)}
    methods = sorted(methods, key=lambda method: method_rank[method])
    tasks = task_columns(rows)

    lines = [
        "% Generated by paper_utils/hybrid/generate_downstream_task_grid.py.",
        "% Values are mean centered task accuracies multiplied by 100.",
        "\\begingroup",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\scriptsize",
        "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}l" + "r" * len(methods) + "@{}}",
        "\\toprule",
        "Task & " + " & ".join(METHOD_SHORT_LABEL[method] for method in methods) + " \\\\",
        "\\midrule",
    ]
    for task in tasks:
        means = {
            method: st.mean(data[method][task][seed] for seed in sorted(data[method][task]))
            for method in methods
        }
        best, second = _top2(means)
        cells = [TASK_LABEL[task], *[_cell(means[method], method, best, second) for method in methods]]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular*}", "\\endgroup"]

    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_TEX}")
    print(OUT_TEX.read_text())


if __name__ == "__main__":
    main()
