#!/usr/bin/env python3
"""Generate the appendix downstream seed-summary table."""

import statistics as st
from collections import defaultdict

from paper_utils.hybrid.downstream_results import (
    METHOD_LABEL,
    METHOD_ORDER,
    PAPER_SEEDS_PER_METHOD,
    load_metric_data,
    paper_methods,
)
from paper_utils.hybrid.utils import paper_table_path

OUT_TEX = paper_table_path("table_downstream_seeds.tex", appendix=True, extra=True)


def _load() -> dict[str, dict[int, dict[str, float]]]:
    metric_data = load_metric_data()
    data: dict[str, dict[int, dict[str, float]]] = defaultdict(dict)
    for method in paper_methods(metric_data):
        for seed in sorted(metric_data[method]["core"]):
            data[method][seed] = {
                "core": metric_data[method]["core"][seed],
                "val_bpb": metric_data[method]["val_bpb"][seed],
            }
    return data


def _ordered_methods(rows: dict[str, dict[int, dict[str, float]]]) -> list[str]:
    return [method for method in METHOD_ORDER if method in rows]


def _mean(rows: dict[str, dict[int, dict[str, float]]], method: str, metric: str) -> float:
    return st.mean(row[metric] for row in rows[method].values())


def _metric_values(rows: dict[str, dict[int, dict[str, float]]], method: str, metric: str) -> list[float]:
    return [rows[method][seed][metric] for seed in sorted(rows[method])]


def _delta_vs_best(value: float, best: float, *, higher_better: bool) -> float:
    if higher_better:
        return (value - best) / best * 100.0
    return (best - value) / best * 100.0


def _delta_cell(value: float, best: float, *, is_best: bool, higher_better: bool) -> str:
    delta = _delta_vs_best(value, best, higher_better=higher_better)
    if is_best:
        return "--"
    return f"{delta:+.2f}\\%"


def _panel(
    rows: dict[str, dict[int, dict[str, float]]],
    methods: list[str],
    metric: str,
    title: str,
    *,
    higher_better: bool,
    fmt: str,
) -> list[str]:
    means = {method: _mean(rows, method, metric) for method in methods}
    best_mean = max(means.values()) if higher_better else min(means.values())
    sorted_methods = sorted(methods, key=lambda method: _mean(rows, method, metric), reverse=higher_better)
    lines = [
        "\\begin{tabular}{@{}lrrrrrr@{}}",
        "\\toprule",
        f"\\multicolumn{{7}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\",
        "Method & $n$ & min & max & mean & std & $\\Delta$ vs Best \\\\",
        "\\midrule",
    ]
    for method in sorted_methods:
        values = _metric_values(rows, method, metric)
        mean = _mean(rows, method, metric)
        is_best = mean == best_mean
        cells = [
            METHOD_LABEL[method],
            str(len(values)),
            fmt.format(min(values)),
            fmt.format(max(values)),
            fmt.format(mean),
            fmt.format(st.stdev(values)),
            _delta_cell(mean, best_mean, is_best=is_best, higher_better=higher_better),
        ]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return lines


def main() -> None:
    rows = _load()
    methods = _ordered_methods(rows)
    lines = [
        "% Generated by paper_utils/hybrid/generate_downstream_seed_table.py.",
        "% Requires \\usepackage{booktabs}.",
        f"% Uses the {PAPER_SEEDS_PER_METHOD} lowest seed ids per method from results/downstream/d24_master_results.tsv.",
        "% Delta vs Best is signed so negative values are worse than the best method.",
        "\\setlength{\\tabcolsep}{4pt}",
        *_panel(
            rows,
            methods,
            "val_bpb",
            "bpb (held-out bits/byte; lower is better)",
            higher_better=False,
            fmt="{:.6f}",
        ),
        "\\vspace{0.65em}",
        *_panel(
            rows,
            methods,
            "core",
            "CORE centered accuracy (higher is better)",
            higher_better=True,
            fmt="{:.4f}",
        ),
    ]
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_TEX}")
    print(OUT_TEX.read_text())


if __name__ == "__main__":
    main()
